require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Api::ProgramsController do

  # This should return the minimal set of attributes required to create a valid
  # Api::Program. As you add validations to Api::Program, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all api_programs as @api_programs" do
      program = Api::Program.create! valid_attributes
      get :index
      assigns(:api_programs).should eq([program])
    end
  end

  describe "GET show" do
    it "assigns the requested program as @program" do
      program = Api::Program.create! valid_attributes
      get :show, :id => program.id.to_s
      assigns(:program).should eq(program)
    end
  end

  describe "GET new" do
    it "assigns a new program as @program" do
      get :new
      assigns(:program).should be_a_new(Api::Program)
    end
  end

  describe "GET edit" do
    it "assigns the requested program as @program" do
      program = Api::Program.create! valid_attributes
      get :edit, :id => program.id.to_s
      assigns(:program).should eq(program)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Api::Program" do
        expect {
          post :create, :program => valid_attributes
        }.to change(Api::Program, :count).by(1)
      end

      it "assigns a newly created program as @program" do
        post :create, :program => valid_attributes
        assigns(:program).should be_a(Api::Program)
        assigns(:program).should be_persisted
      end

      it "redirects to the created program" do
        post :create, :program => valid_attributes
        response.should redirect_to(Api::Program.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved program as @program" do
        # Trigger the behavior that occurs when invalid params are submitted
        Api::Program.any_instance.stub(:save).and_return(false)
        post :create, :program => {}
        assigns(:program).should be_a_new(Api::Program)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Api::Program.any_instance.stub(:save).and_return(false)
        post :create, :program => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested program" do
        program = Api::Program.create! valid_attributes
        # Assuming there are no other api_programs in the database, this
        # specifies that the Api::Program created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Api::Program.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => program.id, :program => {'these' => 'params'}
      end

      it "assigns the requested program as @program" do
        program = Api::Program.create! valid_attributes
        put :update, :id => program.id, :program => valid_attributes
        assigns(:program).should eq(program)
      end

      it "redirects to the program" do
        program = Api::Program.create! valid_attributes
        put :update, :id => program.id, :program => valid_attributes
        response.should redirect_to(program)
      end
    end

    describe "with invalid params" do
      it "assigns the program as @program" do
        program = Api::Program.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Api::Program.any_instance.stub(:save).and_return(false)
        put :update, :id => program.id.to_s, :program => {}
        assigns(:program).should eq(program)
      end

      it "re-renders the 'edit' template" do
        program = Api::Program.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Api::Program.any_instance.stub(:save).and_return(false)
        put :update, :id => program.id.to_s, :program => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested program" do
      program = Api::Program.create! valid_attributes
      expect {
        delete :destroy, :id => program.id.to_s
      }.to change(Api::Program, :count).by(-1)
    end

    it "redirects to the api_programs list" do
      program = Api::Program.create! valid_attributes
      delete :destroy, :id => program.id.to_s
      response.should redirect_to(api_programs_url)
    end
  end

end
