# Generated by cucumber-sinatra. (Sat Jul 10 15:46:03 -0400 2010)
ENV['RACK_ENV']='test'

app_file = File.join(File.dirname(__FILE__), '..', '..', 'hackety.rb')
require app_file

require 'capybara'
require 'capybara/cucumber'
require 'spec'
require 'spec/stubs/cucumber'
require 'database_cleaner'
require 'database_cleaner/cucumber'
DatabaseCleaner.strategy = :truncation

Sinatra::Application.app_file = app_file

World do
  Capybara.app = Sinatra::Application
  Capybara.app.set(:environment, :test)
  Capybara.app.set(:raise_errors, true)
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end

Pony.stub(:deliver)

require 'factory_girl'
Dir.glob(File.join(File.dirname(__FILE__), '..', '..', '/factories/*.rb')).each do |factory|
  require factory
end


