# Generated by cucumber-sinatra. (Sat Jul 10 15:46:03 -0400 2010)

app_file = File.join(File.dirname(__FILE__), '..', '..', 'hackety.rb')
require app_file

require 'capybara'
require 'capybara/cucumber'
require 'spec'

Sinatra::Application.app_file = app_file

World do
  Capybara.app = Sinatra::Application
  Capybara.app.set(:environment, :test)
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end

require 'factory_girl'
Dir.glob(File.join(File.dirname(__FILE__), '..', '..', '/factories/*.rb')).each do |factory|
	require factory
end


