# Generated by cucumber-sinatra. (Sat Jul 10 15:46:03 -0400 2010)

require File.join(File.dirname(__FILE__), '..', '..', 'hackety.rb')

require 'capybara'
require 'capybara/cucumber'
require 'spec'

Hackety.set(:environment, :test)

World do
  Capybara.app = Hackety
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end

require 'factory_girl'
Dir.glob(File.join(File.dirname(__FILE__), '..', '..', '/factories/*.rb')).each do |factory|
	require factory
end


