Feature: Hacker management
  Scenario: Following Hackers
    Given there's a hacker with the username "fela"
    And I'm logged in as "steve"
    When I go to the hacker page for "fela"
    And I follow "Follow fela"
    Then I should see "Now following fela."
    And I should be on the hacker page for "steve"
    And I should see "Following: 1"
    And I go to the hacker page for "fela"
    And I should see "Followers: 1"
  Scenario: Seeing Followers
    Given there's a hacker with the username "steve"
    And there's a hacker with the username "fela"
    And the hacker "steve" is following the hacker "fela"
    When I go to the hacker page for "fela"
    And I follow "1"
    Then I should see "steve"
  Scenario: Seeing Following
    Given there's a hacker with the username "steve"
    And there's a hacker with the username "fela"
    And the hacker "steve" is following the hacker "fela"
    When I go to the hacker page for "steve"
    And I follow "1"
    Then I should see "fela"
  Scenario: Unfollowing a Hacker
    Given I'm logged in as "steve"
    And there's a hacker with the username "fela"
    And the hacker "steve" is following the hacker "fela"
    When I go to the hacker page for "fela"
    And I follow "Unfollow fela"
    Then I should be on the hacker page for "steve"
    And I should see "No longer following fela."
    And I should see "Following: 0"
